[book]
title = "You & All My Stories"
authors = ["E.L. Muffin"]
language = "en"
src = "book"

[build]
build-dir = "_build"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ericg/all-my-stories"
additional-css = ["theme/custom.css"]
additional-js = ["theme/title-fix.js"]
no-section-label = true
